# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run static analysis, unit tests, and integration tests and a dev-flavor ios build"
  lane :validate_pr do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
#       sh("flutter test")
      sh("cd ios && bundle exec pod install")
      sh("flutter build ios -t lib/main_dev.dart --no-codesign --dart-define=FLAVOR=dev")
    end
  end
end