# update_fastlane

default_platform(:android)

platform :android do
  desc "Run static analysis, unit tests, and integration tests and a dev-flavor apk build"
  lane :validate_pr do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
#       sh("flutter test")
      sh("flutter build apk --flavor dev -t lib/main_dev.dart")

    end
  end
 end


#   desc "build the release apk and upload to firebase app distribution"
#   lane :distribute_release_to_firebase do
#     flutter_root = File.expand_path("../..", __dir__)
#     Dir.chdir(flutter_root) do
#       sh("flutter pub get")
#       sh("flutter build apk --flavor dev -t lib/main_dev.dart")
#     end
#
#     apk_path = File.join(flutter_root, "build", "app", "outputs", "flutter-apk", "app-dev-release.apk")
#     firebase_app_distribution(
#       app: "1:624493250471:android:8443e2ffcd48214a405882",
#       firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
#       groups: "testers",
#       android_artifact_type: "APK",
#       release_notes: "First Fastlane Firebase Distribution",
#       android_artifact_path: apk_path
#     )
#   end
#
#   desc "build the release apk and upload to firebase app distribution for prod"
#   lane :distribute_prod_to_firebase do
#     flutter_root = File.expand_path("../..", __dir__)
#     Dir.chdir(flutter_root) do
#       sh("flutter pub get")
#       sh("flutter build apk --flavor prod -t lib/main_prod.dart")
#     end
#
#     apk_path = File.join(flutter_root, "build", "app", "outputs", "flutter-apk", "app-prod-release.apk")
#     firebase_app_distribution(
#       app: "1:624493250471:android:b7227796a71bcba4405882",
#       firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
#       groups: "prod",
#       android_artifact_type: "APK",
#       release_notes: "Prod Release",
#       android_artifact_path: apk_path
#     )
#   end
# end