# update_fastlane

default_platform(:android)

platform :android do
  desc "Run static analysis, unit tests, and integration tests and a dev-flavor apk build"
  lane :validate_pr do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
      sh("flutter test")
      sh("flutter build apk --flavor dev -t lib/main_dev.dart")
    end
  end

  desc "build the release apk and upload to firebase app distribution"
  lane :distribute_release_to_firebase do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
      sh("flutter test")
      build_cmd = "flutter build apk --flavor dev -t lib/main_dev.dart"
      if (bn = ENV["WORKFLOW_RUN_NUMBER"])  && !bn.strip.empty?
        build_cmd += " --build-number=#{bn.strip}"
      end
      sh(build_cmd)
    end

    apk_path = File.join(flutter_root, "build", "app", "outputs", "flutter-apk", "app-dev-release.apk")
    firebase_app_distribution(
      app: "1:123158677657:android:569a5abe85e6daa8ded008",
      firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
      groups: "dev",
      android_artifact_type: "APK",
      release_notes: "First Fastlane Firebase Distribution",
      android_artifact_path: apk_path
    )
  end

  desc "build the release apk and upload to firebase app distribution for prod"
  lane :distribute_prod_to_firebase do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter analyze")
      sh("flutter test")
      build_cmd = "flutter build apk --flavor prod -t lib/main_prod.dart"
      if (bn = ENV["WORKFLOW_RUN_NUMBER"])  && !bn.strip.empty?
        build_cmd += " --build-number=#{bn.strip}"
      end
      sh(build_cmd)
    end

    apk_path = File.join(flutter_root, "build", "app", "outputs", "flutter-apk", "app-prod-release.apk")
    firebase_app_distribution(
      app: "1:477157615956:android:ce8031bcf92178e0e940c1",
      firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
      groups: "prod",
      android_artifact_type: "APK",
      release_notes: "Prod Release",
      android_artifact_path: apk_path
    )
  end

  desc "build the release apk and upload to firebase app distribution for staging"
    lane :distribute_stag_to_firebase do
      flutter_root = File.expand_path("../..", __dir__)
      Dir.chdir(flutter_root) do
        sh("flutter pub get")
        sh("flutter analyze")
        sh("flutter test")
        build_cmd = "flutter build apk --flavor stag -t lib/main_stag.dart"
        if (bn = ENV["WORKFLOW_RUN_NUMBER"])  && !bn.strip.empty?
          build_cmd += " --build-number=#{bn.strip}"
        end
        sh(build_cmd)
      end

      apk_path = File.join(flutter_root, "build", "app", "outputs", "flutter-apk", "app-stag-release.apk")
      firebase_app_distribution(
        app: "1:8389433546:android:53825cc01a98828a3b3c33",
        firebase_cli_token: ENV.fetch("FIREBASE_CLI_TOKEN"),
        groups: "stag",
        android_artifact_type: "APK",
        release_notes: "Prod Release",
        android_artifact_path: apk_path
      )
    end
end